name: Build
on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
          sudo apt-get install -y android-sdk-build-tools  # Add Android build tools
        shell: bash

      - name: Install Buildozer
        run: pip install buildozer

      - name: Configure Buildozer
        run: buildozer init

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./bin/myapp-*-release.apk  # Adjust the path as needed
