name: Build APK

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can specify the Python version you need

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libjpeg-dev \
          libtiff-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev
      shell: bash

    - name: Install Buildozer via Pip
      run: pip install buildozer

    - name: Install Android Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk-build-tools
      shell: bash

    - name: Install Cython
      run: pip install cython

    - name: Configure buildozer
      run: buildozer init
      continue-on-error: true

    - name: Build APK
      run: buildozer android debug
