name: Build APK

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # You can specify the Python version you need

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libjpeg-dev \
          libtiff-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev
        pip install --upgrade buildozer
      shell: bash

    - name: Configure buildozer
      run: buildozer init
      continue-on-error: true

    - name: Copy buildozer(2).spec
      run: cp build.spec buildozer(2).spec
      working-directory: .github/workflows  # Adjust the path to your buildozer.spec

    - name: Build APK
      run: buildozer android debug

